[package]
name = "cpu_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
mnist = "0.6.0"
ndarray = "0.15.6"
rand = "0.8.5"
rayon = "1.8.1"
wgpu_test = { path = "../wgpu_test" }
