name: Rust CI

on:
  push:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint with Clippy
      run: cargo clippy -- -D warnings
      working-directory: ./rust
    - name: Check format with rustfmt
      run: cargo fmt -- --check
      working-directory: ./rust

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      working-directory: ./rust

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --workspace --verbose
      working-directory: ./rust

  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Audit dependencies
      run: cargo audit
      working-directory: ./rust
